CREATE SCHEMA IF NOT EXISTS BOOK_REST_SERVICE;
SET SCHEMA BOOK_REST_SERVICE;

CREATE TABLE IF NOT EXISTS AUTHOR(
    author_id BIGINT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOK(
    book_id BIGINT AUTO_INCREMENT PRIMARY KEY,
	price DOUBLE NOT NULL,
	name VARCHAR(60) NOT NULL,
	author_id BIGINT,
	FOREIGN KEY (author_id) REFERENCES AUTHOR(author_id)
);

CREATE TABLE IF NOT EXISTS WISHLIST(
    wishlist_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    count BIGINT NOT NULL,
	book_id BIGINT NOT NULL,
	FOREIGN KEY (book_id) REFERENCES BOOK(book_id)
);

CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;
